### Instalar a extensão REST CLIENT
### Criar um arquivo .http

### Raiz do Projeto
GET http://localhost:5195

### Listar Produtos
GET http://localhost:5195/api/produto/listar

### Cadastrar Produto
POST http://localhost:5195/api/produto/cadastrar
Content-Type: application/json

{
    "nome" : "Notebook"
}